[package]
name = "oxide_pinger"
version = "0.1.0"
authors = ["Tim Buchwaldt <tim@buchwaldt.ws>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oping = "0.4.0"
prometheus_exporter = "0.7"
lazy_static = "1.4.0"